---
- name: Install OpenJDK
  become: no
  hosts: "{{ elastic }}"
  vars:
    java_version: 1.8.0
  tasks:
    - name: Instalacion de Java JDK
      yum: name=java-{{ java_version }}-openjdk state=present
